"use client"
import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { TaskProvider } from "@/context/TaskContext";
import { Video } from "@/components/Video";
import Mapa from "@/components/Mapa";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Contiene todas las paginas, lo que se agregue aqui aparecera en todas las paginas
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="mx-14">
          {/* <TaskProvider> */}
            <Navbar />
            {/* <Video /> */}
            {/* <Mapa /> */}
            {children}
          {/* </TaskProvider> */}
        </div>
      </body>
    </html>
  );
}
